services:
  - name: etcd
    image: quay.io/coreos/etcd:latest
    command:
    - etcd
    - -listen-client-urls
    - http://0.0.0.0:2379
    - -advertise-client-urls
    - http://0.0.0.0:2379
    capabilities:
     - all
    net: host
  - name: apiserver
    image: linuxkit/apiserver:0290a9addca287ab3bd132df7a177d51837115ad
  - name: controller-manager
    image: linuxkit/controller-manager:2c46e2abb7a932faf8b4ab279fe3f22cf6cd97f8
  - name: scheduler
    image: linuxkit/scheduler:d2772ed900dd11c21b68e4f1bb9a010538712a3c
files:
  - path: /etc/kubelet.sh.conf
    contents: ""
